- src/Assignments/SimpleProblemPage.tsx
baby PR - problem numbering seems to be fixed again somewhere else - we don't need this +1 any longer...
> fixing displayed problem number

- src/Assignments/SimpleProblemPage.tsx
> itsy bitsy commit

- src/Assignments/SimpleProblemPage.tsx
> not another one of these

- src/Assignments/ProblemIframe.tsx
- tsconfig.json
This code is pulled from and tweaked from the renderer
> RED-85 Added and integrated new interceptor code

- package-lock.json
- package.json
- src/Assignments/ProblemIframe.tsx
- src/Courses/CourseCreation/TopicCreationModal.tsx
- tsconfig.json
> pull up to the bumper 1.0.2

- src/Assignments/ProblemIframe.tsx
Removed the url encode
Removed the extra json we were sending (a renderer bug exposed this
issue)
Removed extra content header
> RED-88 Removed work arounds for backend parsing

- src/NavWrapper/ProvideFeedback.tsx
@red-tt-bear I realize this is probably the short and messy way to do it. I could add a new query parameter to the backend instead.
> Added the URL to the tail-end of the description for the provide feedback

- src/Assignments/ProblemIframe.tsx
This was causing the first grade in the list to update
> RED-137 Fixed issue where load listeners were inserted twice

- src/Courses/CourseDetailsTabs/StatisticsTab.tsx
Omit the word average for users
Changed Completed to mastered
> RED-152 Corrected statistics header

- src/Assignments/ProblemIframe.tsx
submission now blocked for 4 seconds following any successful submit
'submitted at:' is only updated on 'submitAnswers' click (in case of other buttons)
> preventDefault all 'submit' and check clicked btn

- src/Assignments/ProblemIframe.tsx
> lower delay for geogebra updates

- src/Assignments/ProblemIframe.tsx
please let this be the final nail in this coffin 💀
> prevent first-submit spamming

- src/Assignments/SimpleProblemPage.tsx
so glad I left that comment ;P
> don't prompt for new version after endDate

- src/Courses/TopicSettings/CommonSettings.tsx
- src/Courses/TopicSettings/ExamSettings.tsx
- src/Courses/TopicSettings/GenericFormInputs.tsx
- src/Courses/TopicSettings/ProblemSettings.tsx
- src/Courses/TopicSettings/RendererPreview.tsx
(Almost) All requested changes in RED-226 + overrides to date-picker warnings + hiding settings irrelevant for exams
Missing:
* ENUM for restricting grades view on exam submission
* "cancel" button for reverting changes on the topic settings page
> RED-226 form instructions overhaul

- src/Courses/CourseInterfaces.tsx
- src/Courses/TopicGrades/GradeInfoHeader.tsx
- src/Courses/TopicGrades/GradingPage.tsx
* fix workbook selection for non-exams -- thanks gib
* fix topic info header layout to remove extra vertical spacing
* reorganize topic info header into statistics/grades
> grading layout update + workbook fix

- src/Assignments/SimpleProblemPage.tsx
when backend returns no problems, use the corresponding error message (with generic fallback message)
> provide more info when no problems in topic

- src/Courses/CourseInterfaces.tsx
- src/Courses/TopicSettings/ProblemSettings.tsx
the first path in the additionalPaths array.
> Fixed typing, now has the frontend sharing the wwPath for homeworks and

- src/Assignments/SimpleProblemPage.tsx
enrolled in the course views the topic.
> RED-254 Added users from the course to guard logs when a user that's not

- src/Assignments/ProblemIframe.tsx
@PanopticaRising was clutch on this fix
> problem iframe formURL mismatch

- src/APIInterfaces/BackendAPI/RequestTypes/UserRequestTypes.ts
- src/APIInterfaces/BackendAPI/Requests/UserRequests.ts
- src/APIInterfaces/BackendAPI/ResponseTypes/UserResponseTypes.ts
- src/Login/RegisterForm.tsx
> RED-107 Typed the registration call

- src/Assignments/ProblemIframe.tsx
added renderedHTML to the error log, and styled the error message (+ instructions to refresh)
> elaborate on problemMainForm error

- src/APIInterfaces/BackendAPI/RequestTypes/CourseRequestTypes.ts
- src/APIInterfaces/BackendAPI/Requests/CourseRequests.ts
- src/APIInterfaces/BackendAPI/ResponseTypes/CourseResponseTypes.ts
- src/Courses/EnrollUserPage.tsx
Downgraded invalid logger.error
Set the error message as it comes back from the api
> RED-107 Typed enrollment call

- src/APIInterfaces/BackendAPI/RequestTypes/UserRequestTypes.ts
- src/APIInterfaces/BackendAPI/Requests/UserRequests.ts
- src/APIInterfaces/BackendAPI/ResponseTypes/UserResponseTypes.ts
- src/Courses/EnrollUserPage.tsx
- src/Login/VerificationLandingPage.tsx
> RED-107 Typed verification

- src/Account/AccountDetailsPage.tsx
- src/Assignments/ProblemEditor.tsx
- src/Courses/CourseDetailsTabs/GradesTab.tsx
- src/Courses/CourseList.tsx
- src/Courses/CoursePage.tsx
- src/Courses/EnrollUserPage.tsx
- src/Enums/UserRole.tsx
- src/Login/ForgotPasswordButtonAndModal.tsx
- src/Login/LoginForm.tsx
- src/Login/RegisterForm.tsx
- src/Login/ResendVerificationModal.tsx
- src/Login/VerificationLandingPage.tsx
- src/NavWrapper/NavWrapper.tsx
- src/Utilities/LocalPreferences.ts
- src/Utilities/Logger.ts
Make sure to review my other pr first
> Feature/red 301 user UUID

- src/Courses/CourseDetailsTabs/StatisticsTab.tsx
this is my bad -- I added the loading state and didn't account for all situations to setLoading(false)
> fix setLoading state

- src/Assignments/ProblemIframe.tsx
On load bows out immediately if:
renderedHTML is ''
renderedHTML !== iframeHTML
A new request is pending
> RED-318 Fixed loading state

- src/Courses/TopicGrades/GradeInfoHeader.tsx
fix error with mismatching user/grade/workbook state in grade info header
> clear info when grade is null

- src/APIInterfaces/BackendAPI/ResponseTypes/CourseResponseTypes.ts
- src/Courses/TopicGrades/AttachmentsPreview.tsx
- src/Courses/TopicGrades/GradingPage.tsx
- src/Courses/TopicGrades/PrintEverything.css
- src/Courses/TopicGrades/PrintEverything.tsx
- src/Extensions/DateExtension.ts
Added an extension to date to standardize the way we're showing the dates to users.
> Added attachment timestamps using the updatedAt field.

- src/APIInterfaces/BackendAPI/RequestTypes/CourseRequestTypes.ts
- src/APIInterfaces/BackendAPI/Requests/CourseRequests.ts
- src/Assignments/SimpleProblemPage.tsx
- src/Courses/CourseInterfaces.tsx
will need to do testing on this with the openlab -- requested to wait until after this week due to finals.
> enable ask for help for citytech students only

- src/Assignments/ProblemIframe.tsx
stop problem iframe race condition with event listeners
> some machines are faster than others

- src/APIInterfaces/BackendAPI/Requests/CourseRequests.ts
- src/Assignments/ProblemEditor.tsx
- src/Assignments/ProblemEditorAssetUploadButton.tsx
- src/Courses/CourseDetailsTabs/TopicsTab.tsx
Fixed bug with error handling for archive uploads
Added asset upload to the editor
> RED-10 Added asset upload

- src/Assignments/SimpleProblemPage.tsx
> RED-378 Disabled sma if there are no versions

- src/APIInterfaces/BackendAPI/Requests/CourseRequests.ts
- src/Assignments/ProblemEditor.tsx
Duplicate random seed prevented submit from using the same random seed
Not including the load path prevented assets from showing
> Added context path and deleted duplicate random seed

- src/APIInterfaces/BackendAPI/RequestTypes/CourseRequestTypes.ts
- src/APIInterfaces/BackendAPI/Requests/CourseRequests.ts
- src/Account/StudentTopicPreferences.tsx
- src/Courses/CourseCreation/CourseTarballImportButton.tsx
- src/Utilities/LocalPreferences.ts
Exams use buckets, this configuration allows you to keep or remove those
topics
> RED-448 Added option to keep buckets as topics

- src/APIInterfaces/BackendAPI/RequestTypes/CourseRequestTypes.ts
- src/APIInterfaces/BackendAPI/Requests/CourseRequests.ts
- src/Courses/CourseDetailsTabs/GradesTab.tsx
Also switched to typed request
> RED-410 Added course id to filter

- src/Assignments/ProblemIframe.tsx
- src/Assignments/SimpleProblemPage.tsx
- src/Courses/CourseInterfaces.tsx
- src/Enums/AssignmentEnums.tsx
keeping it simple - updating save status is too much gibbery for now...
> re-fetch problems after exam submission

- src/Assignments/ProblemIframe.tsx
- src/Assignments/SimpleProblemPage.tsx
minor correction - fixes unnecessary re-render on first currentProblemState update.
useEffect now watches specific parameters of the problem object rather than the whole problem
> remove outdated useEffect trigger

- src/APIInterfaces/BackendAPI/RequestTypes/CourseRequestTypes.ts
- src/Assignments/ProblemDetails.tsx
- src/Assignments/ProblemEditor.tsx
- src/Assignments/ProblemIframe.tsx
would witespace clean up an spelling fixes be helpful?
> fix a couple of spelling issues

- src/Courses/TopicSettings/CommonSettings.tsx
- src/Courses/TopicSettings/TopicSettings.tsx
Before save the type is incorrectly string instead of date, which is ok
because we have toMoment on both
After save the type is incorrectly moment instead of date, which is what
was breaking it
Wrapped the value in moment to make it work consistently
Added error handling so we can see when it fails and give indication to
the user
Also added Rederly- to export button since it is a rederly def file
(should work as regular def file but has a couple of extra props)
> RED-499 Fixed export def file

- src/Components/MomentReacter.tsx
- src/Courses/CourseDetailsTabs/OverrideGradeModal.tsx
- src/Courses/TopicGrades/GradingPage.tsx
- src/Courses/TopicSettings/ExamSettings.tsx
- src/Extensions/LodashMixins.ts
Is one more round of spelling updates OK?
> fix some spelling issues

- src/APIInterfaces/BackendAPI/Requests/CourseRequests.ts
- src/Assignments/AttachmentsSidebar.tsx
Added a warning log for debugging.
> fix: Use POST to cachebust get upload-url request.

- src/Components/VerticalDivider.tsx
- src/Courses/TopicSettings/ProblemSettingsViewEditPanels.tsx
Mentioned here: https://github.com/mui-org/material-ui/issues/25321
> feat: Added a generic component to get a vertical divider effect.

- package-lock.json
- package.json
- src/Courses/TopicSettings/TopicSettings.tsx
- src/Courses/TopicSettings/TopicSettingsPage.tsx
Updated react-hook-forms for bugfixes.
> fix: Fixed unsaved changes message showing up without changes.

- src/Assignments/SimpleProblemPage.tsx
fix: Caught a bug where 0 scores broke formatting.
> fix: Calculate the total weight to generate the percent.

- src/Contexts/VersionContext.tsx
- src/Courses/CourseInterfaces.tsx
- src/NavWrapper/NavWrapper.tsx
- src/Utilities/VersionCheck.tsx
- src/index.tsx
feat: Added version context with checks on an interval for new versions.
> refactor: Changed VersionCheck to display the version in the footer.
